    ["spray"] = {
        name = "spray",
        label = "Spraycan",
        weight = 300,
        stack = true,
        close = false,
        description = "A spray can of paint",
    },
    ["spray_remover"] = {
        name = "spray_remover",
        label = "Spray Removal Kit",
        weight = 300,
        stack = true,
        close = true,
        description = "A spray paint removal kit",
    },
